### ISSUE TITLE
Support generic sequence hotkeys

### ISSUE THREAD

**Issue by anstosa** [tgrosinger/leader-hotkeys-obsidian#10]
Would love to extend this to sequence style hotkeys in addition to ones just starting with a fixed leader key. For example, my leader key is `ctrl+b` but I'm used to creating a new vertical split with `ctrl+w v`.

**Comment by tgrosinger** [comment]
This is a tricky one. Currently I am using Obsidian hotkeys to call the plugin by registering the leader as a command. If there were multiple leaders, it would need to register multiple commands. Probably not a very good experience.

I could side-step the Obsidian hotkeys and listen for keystrokes myself (I do that to listen for enter and tab in the Advanced Tables plugin), but then there would not be a method of warning a user when their leader conflicts with another hotkey.

I'll have to think about this one some more. There is a new way of setting up hotkeys that I need to look into for https://github.com/tgrosinger/advanced-tables-obsidian/issues/53 so maybe that will produce something interesting.

**Comment by anstosa** [comment]
Also worth considering a library for this. [Mousetrap](https://craig.is/killing/mice) is the canonical JS solution. It's tiny and supports sequence keys out of the box.

**Comment by lyndhurst** [comment]
:+1:  I would also find multiple leaders / hotkey sequences a great enhancement.
Thanks for your time.

**Comment by Ampa** [comment]
This would be super useful.
I'd like to have all my Advanced Tables shortcuts start Ctrl+T
Pane Relief start Ctrl + R for example.

**Comment by WhiteNoiseDev** [comment]
Do you think it's possible to support a complete hotkey as second key? To support something like ctrl+b ctrl+k?

**Comment by tgrosinger** [comment]
Resolved in #19
