### ISSUE TITLE
simple key chords

### ISSUE THREAD

**Issue by DannyDies** [tgrosinger/leader-hotkeys-obsidian#14]
Hello! It is possible to add simple key chords? Just more then one char aftrer leader without mods, like:
- `<leader>ww`
- `<leader>ws`
- etc

**Comment by tgrosinger** [comment]
This sounds achievable, however I have not been putting time into this plugin for a while. I'll leave this here though in case someone else wants to take a go at it.

**Comment by diogox** [comment]
Not my field of expertise, so I don't think I can help. But I too would like to see this implemented. It would make the move from emacs a bit smoother :)

**Comment by tgrosinger** [comment]
Resolved in #19
