### ISSUE TITLE
Broken in new Obsidian live preview editor

### ISSUE THREAD

**Issue by Sigbert11** [tgrosinger/leader-hotkeys-obsidian#18]
**the problem**
leader key recognition lost in the now new standard Obsidian "live preview editor"

**To Reproduce**
switching back to  legacy editor restores leader key functionality

**context**
 - OS: macOS monterey
 - Obsidian Version: 13.24
 - Leader Hotkeys Version: 0.1.3

**Comment by hellen-dorandt89** [comment]
I can confirm this same issue too,
any chance we will see a fix soon?  Thanks

**Comment by thesulaj** [comment]
Unfortunately, #19 did not resolve this for me in the new editor. When I switch back to the old editor, everything works again. My hotkeys are:
- ctrl-w h
- ctrl-w l

# Context
OS: macOS monterey
Obsidian Version: 0.15.9
Leader Hotkeys Version: 0.2.0
