### ISSUE TITLE
MatchHandler is logging a keypress to the console on every keystroke

### ISSUE THREAD

**Issue by nazgul** [tgrosinger/leader-hotkeys-obsidian#27]
**Describe the bug**
```
        this.handleKeyDown = function (event) {
	    var keypress = KeyPress.fromEvent(event);
	    console.log(keypress);
```

**To Reproduce**
1. Open the debug console
2. Type

**Expected behavior**
Please don't leave debug logs in!

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOSS
 - Obsidian Version: N/A
 - Leader Hotkeys Version: 0.2.0

**Additional context**
Great plugin otherwise! Love having my vi pane movement controls back.

**Comment by eth-p** [comment]
It looks like #36 is planning on fixing this, but there's no idea when that's going to be merged. Last activity on this repo has been 10 months ago as of this comment, unfortunately.

We can use the filter rule `-url:plugin:leader-hotkeys-obsidian` to hide the messages in the meantime, at least.

**Comment by tgrosinger** [comment]
PR has been merged and a new release made. Sorry about that!
