### ISSUE TITLE
leader key not working yet

### ISSUE THREAD

**Issue by santiyounger** [tgrosinger/leader-hotkeys-obsidian#5]
Hey,
super excited to use this plugin

I understand that it doesn't work in preview mode for now, so I'm doing it in edit mode.
the problem I have is that if I use the default keybinding `ctrl` + `b` Obisdian uses that for making text bold.

Of course the good thing is one can remmap this.

I tried using a few other shortcut, such as 
`alt` + `q`
`alt` + `s`
`ctrl` + `u`

but none of them worked

I removed the default Obsidian bold so that  `leader-hotkeys-obsidian` can use `ctrl` + `b` but it's not working either.

I'm testing  the default mapping such as `leader` + `h` to `focus on pane on left`
I open many panes to test it, but I don't get any results.

# Specs
I'm on Linux
Manjaro XFCE with Awesome Window Manager
leader-hotkeys-obsidian  0.1.1
Obisdian 0.9.20

Thanks, looking forward to using this everyday

**Comment by tgrosinger** [comment]
Hi @santiyounger, just to check can you confirm that this is where you are changing your leader hotkey?

![leader](https://user-images.githubusercontent.com/597386/101409776-4400ec00-38d6-11eb-91ad-06b377f6a47b.png)

And once you change the leader hotkey, you should see that reflected in the settings page text. See how the leader has been changed to "Mod+w" on the settings page in this example?

![leader-settings](https://user-images.githubusercontent.com/597386/101409928-80cce300-38d6-11eb-8c9d-3bfb4723c53c.png)

Let me know if that is working for you so far. If that is working then we can diagnose why using the hotkeys is not working.

**Comment by santiyounger** [comment]
Hey, 
Thanks for taking a look at this,

Yes, that's where I'm mapping the hotkeys indeed

![image](https://user-images.githubusercontent.com/51902730/101516253-405c7c00-394d-11eb-8079-3cfcb503d949.png)

![image](https://user-images.githubusercontent.com/51902730/101516316-5a965a00-394d-11eb-828f-4c4cfb9483b4.png)

It didn't work with `ctrl` + `w` either (which is an obsidian default for closing windows) I did unmap the original `ctrl` + `w` to test.

I'm also curious if there was any reason to use `ctrl` + `b` as the default leader key (considering it's a default for bolding) Just out of curiosity, do you remove `ctrl` + `b` for bolding out of your default obsidian hotkeys?

Ideally I'd like to map it to `space` as leader, since I'm so used to it, is there any way for this to be possible (I understand if it's an obisidian limitation, which seems to be the case)

Feel free to let me know if there's anything more you'd need me to share to figure this out.

I'd be curious to know if it's an issue with Linux perhaps, or maybe a conflict with other plug ins? I did make sure it's not a conflict with other existing hotkeys, since I did a lot of different tests to make sure it wasn't that.

Thanks for your time!

**Comment by tgrosinger** [comment]
Hmm, yeah maybe I should change the default. I have it set to <kbd>ctrl</kbd>+<kbd>b</kbd> because that's the leader key I use everywhere (I have a Vim plugin that integrates it's panes with tmux panes so I can navigate seamlessly with tmux hotkeys). I do unbind <kbd>ctrl</kbd>+<kbd>b</kbd> from Bold.

Hmm, if it were mapped to space it would only work when you are in normal mode right? I think that is technically possible, but it would be a pretty big departure from how the plugin is written right now. Currently I have using an Obisidan command to trigger the leader, and that would require switching to instead use a CodeMirror keyPress.

I'll play around with it a bit more and see if I can replicate your experience.

**Comment by santiyounger** [comment]
thanks, I get you, yeah if you use `ctrl` + `b` elsewhere it makes sense since it's on your muscle memory, it's the same thing for me with `space` but I understand your plugin uses the default hotkeys instead of vim's CodeMirror, that would be amazing, but of course it would mean a whole different process to make it happen.

Thanks for the help, I was looking further into things, not really sure why it's not working for me yet, let me know if you have any ideas or things to try on my side.

Thank you for the help!

**Comment by Simon-Claudius** [comment]
Thanks for making this plugin @tgrosinger :). 
I also use `space` in other applications, so I'd love to be able to use it in Obsidian, too. 
+1

**Comment by santiyounger** [comment]
> Thanks for making this plugin @tgrosinger :).
> I also use `space` in other applications, so I'd love to be able to use it in Obsidian, too.
> +1

I actually found a workaround for obsidian shortcuts without modifiers
https://forum.obsidian.md/t/unable-to-set-a-hotkey-to-f1/7194/3?u=santi

I'm still unsure if this is possible for a key like `space` but it might work!

**Comment by delucca** [comment]
+1 for `space` as the leader key

**Comment by jaideeprana** [comment]
Yeah, having `space` would be awesome.

**Comment by pwntester** [comment]
> I actually found a workaround for obsidian shortcuts without modifiers
forum.obsidian.md/t/unable-to-set-a-hotkey-to-f1/7194/3?u=santi

I used this trick to define the leader as:

```
  "leader-hotkeys-obsidian:leader": [
    {
      "modifiers": [
      ],
      "key": " "
    }
  ]
```

And it worked great

**Comment by jaideeprana** [comment]
Worked like a charm :)

For me, the name of the file was hotkeys.json file.

**Comment by pwntester** [comment]
I just found out that this approach will prevent `<space>` from working on insert mode :(

**Comment by jaideeprana** [comment]
😭

**Comment by huyz** [comment]
On macOS, `ctrl-w` only works for `ctrl-w k` but not for `h,j,l` for some reason

**Comment by ne1114** [comment]
> > I actually found a workaround for obsidian shortcuts without modifiers
> > forum.obsidian.md/t/unable-to-set-a-hotkey-to-f1/7194/3?u=santi
> 
> I used this trick to define the leader as:
> 
> ```
>   "leader-hotkeys-obsidian:leader": [
>     {
>       "modifiers": [
>       ],
>       "key": " "
>     }
>   ]
> ```
> 
> And it worked great

Thank you so much!

**Comment by canelhasmateus** [comment]
Can we close this issue? @tgrosinger

**Comment by tgrosinger** [comment]
Yeah, seems outdated. I'm not sure that using space as a leader works still, but it seems like that would require tighter integration with the vim-mode somehow.
