### ISSUE TITLE
Leader key conflict

### ISSUE THREAD

**Issue by charles-e** [tgrosinger/leader-hotkeys-obsidian#6]
**Describe the bug**

On macos.  Your default leader key mapping is apple-B.  This conflicts with the (I believe) default apple-B assignment to "Bold Text". The  "bold text" mapping has priority and therefore your plugin does not do anything.  I don't know if you have an API to access existing mappings so you could easily avoid this problem. Still - wonderful plugin.

**Comment by tgrosinger** [comment]
Yeah, very true. I might just remove the default key binding because I think the other one that makes the most sense (mod+w) is also already used for closing the current window.
