### ISSUE TITLE
Allow using Ctrl and Alt as modifier keys in the "followed by" keys

### ISSUE THREAD

**Issue by kankaristo** [tgrosinger/leader-hotkeys-obsidian#9]
Thanks for making the plugin! I was a bit surprised when Obsidian didn't allow keybindings like this by default.

I'm trying to replicate some of my VSCode keybindings, because it's hard to fight muscle memory...

I have my leader key set to `Ctrl+K`.

Moving focus between panes works fine, I have:
- `Ctrl+K →` to focus on pane to the right
- etc.

However, I'd like to bind:
- `Ctrl+K Ctrl+Shift+→` to split vertically
- `Ctrl+K Ctrl+Shift+↓` to split horizontally

But these don't seem to work (the plugin immediately binds `Ctrl` even if it's held down).

I found https://github.com/tgrosinger/leader-hotkeys-obsidian/issues/2, and `Shift` seems to be allowed as a modifier, but `Ctrl` or `Alt` are immediately bound (instead of being used as modifiers).

Also, `Shift` cannot be used as anything except a modifier (not that I'd necessarily want to, I just noticed that's the case).

Would it be possible to only accept the key on the "key up" event?
- If I hold down `Ctrl`, `Alt` or `Shift` and press another key, then release all keys, that would be used as the key.
- If I press and release `Ctrl`, `Alt` or `Shift`, that would become the selected key (not used as modifiers).
    - (you could still bind something like `Ctrl+K Ctrl`, if you really wanted to).

**Comment by tgrosinger** [comment]
@kankaristo That sounds like a great plan and should definitely be doable. Thank you for the suggestion 🙂 

I have not been putting much time into this plugin currently (working on [Slated](https://github.com/tgrosinger/slated-obsidian) right now), so if you would like to attempt those changes and submit a pull request, that would be awesome. If not no worries, I will definitely get back to this one, just might be a little bit.

**Comment by tgrosinger** [comment]
Resolved in #19, however make sure that the none of the steps in the keyboard shortcut are being used by any system commands.
